title: Blackfly
content: []
github: true
purpose:
  - type: contact
    url: 'mailto:contact@blackfly.se'
    label: Contact me
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: need help with intelligence ?
color:
  saturation: 0.4672878
  brandStrength: 0.5053763
  lightness: 0.01612903
  brandColors:
    - '#B1CEE0'
    - '#1D051D'
    - '#F3FEDC'
    - '#AB9484'
    - '#5E6B98'
  rhythmicContrast: 0.7240143
navigation:
  - name: About Us
    id: 6f636db6-774e-46f2-b863-f6a0eb6b35dc
    type: content
analytics:
  google: UA-83678704-1
name: Blackfly
author:
  name: Urban Edlund
  email: urban.edlund@blackfly.se
  url: www.blackfly.se
typography_spectrum: 0.6146954
layout_spectrum: 0.6577061
url: 'http://www.blackfly.se'
