title: Blackfly
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/eabe58d5-ab70-47b8-8e4e-039a4c4781b1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/eabe58d5-ab70-47b8-8e4e-039a4c4781b1.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b852f404-a353-46e8-815e-fef567fee29f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b852f404-a353-46e8-815e-fef567fee29f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose:
  - type: contact
    url: 'mailto:contact@blackfly.se'
    label: Contact me
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: need help with intelligence ?
color:
  saturation: 0.4672878
  brandStrength: 0.8315412
  lightness: 0.01612903
  brandColors:
    - '#B4B8BC'
    - '#1D3969'
    - '#365C89'
    - '#6A7B8C'
    - '#F9F8F3'
  rhythmicContrast: 0.7240143
navigation:
  - name: About Us
    id: 6f636db6-774e-46f2-b863-f6a0eb6b35dc
    type: content
analytics:
  google: UA-83678704-1
name: Blackfly
author:
  name: Urban Edlund
  email: urban.edlund@blackfly.se
  url: www.blackfly.se
typography_spectrum: 0.6146954
layout_spectrum: 0.9820789
url: 'http://www.blackfly.se'
